export const SkillDetails = [
  {
    PhotoSource: "/html5.png",
    PhotoText: "HTML5",
    category: "core",
    badge: "LVL.MAX",
    tag: "Structure",
    speech: "Semantic Backbone 🦴",
    accent: "#E34F26",
  },
  {
    PhotoSource: "/css3.png",
    PhotoText: "CSS3",
    category: "core",
    badge: "PIXEL PRO",
    tag: "Styling",
    speech: "Pixel Perfectionist 🎨",
    accent: "#1572B6",
  },
  {
    PhotoSource: "/js.png",
    PhotoText: "JAVASCRIPT",
    category: "core",
    badge: "CORE ENGINE",
    tag: "Logic",
    speech: "The Dynamic Brain 🧠",
    accent: "#E5A910",
  },
  {
    PhotoSource: "/typeScript.png",
    PhotoText: "TYPESCRIPT",
    category: "core",
    badge: "SUPERPOWERS",
    tag: "Type Safety",
    speech: "Zero Bug Zone 🛡️",
    accent: "#3178C6",
  },
  {
    PhotoSource: "/nextJs.png",
    PhotoText: "NEXT JS",
    category: "frameworks",
    badge: "GO-TO STACK",
    tag: "Full-Stack",
    speech: "Speed Demon 🏎️💨",
    accent: "#000000",
  },
  {
    PhotoSource: "/react.png",
    PhotoText: "REACT NATIVE",
    category: "frameworks",
    badge: "MOBILE APP",
    tag: "Cross-Platform",
    speech: "Pocket Magic 📱✨",
    accent: "#00B4D8",
  },
  {
    PhotoSource: "/tailWind.png",
    PhotoText: "TAILWIND",
    category: "frameworks",
    badge: "TURBO CSS",
    tag: "Utility-First",
    speech: "Styling at Warp Speed ⚡",
    accent: "#06B6D4",
  },
  {
    PhotoSource: "/sass.png",
    PhotoText: "SASS",
    category: "frameworks",
    badge: "PREPROCESSOR",
    tag: "Modular CSS",
    speech: "CSS with Muscles 🦾",
    accent: "#CC6699",
  },
  {
    PhotoSource: "/git.png",
    PhotoText: "GIT",
    category: "tools",
    badge: "TIME TRAVEL",
    tag: "Version Control",
    speech: "Commit & Conquer 💾",
    accent: "#F05032",
  },
  {
    PhotoSource: "/githubLogo.png",
    PhotoText: "GITHUB",
    category: "tools",
    badge: "DEV HQ",
    tag: "Collaboration",
    speech: "The Mothership 🐙",
    accent: "#24292E",
  },
  {
    PhotoSource: "/php.png",
    PhotoText: "PHP",
    category: "core",
    badge: "VETERAN",
    tag: "Backend",
    speech: "Old Faithful 🐘",
    accent: "#777BB4",
  },
  {
    PhotoSource: "/nodeJs.png",
    PhotoText: "NODEJS",
    category: "core",
    badge: "BACKEND",
    tag: "Runtime",
    speech: "Server Power ⚡",
    accent: "#339933",
  },
  {
    PhotoSource: "/mongoDb.png",
    PhotoText: "MONGODB",
    category: "tools",
    badge: "DATABASE",
    tag: "NoSQL DB",
    speech: "Document Vault 🍃",
    accent: "#47A248",
  },
];

export const LearningDetails = [
  {
    PhotoSource: "/blockchain.svg",
    PhotoText: "BLOCKCHAIN DEV",
    badge: "WEB3",
    speech: "Decentralized Architecture",
    accent: "#2563EB",
  },
  {
    PhotoSource: "/mySql.png",
    PhotoText: "MySQL",
    badge: "RELATIONAL",
    speech: "Query Wizardry",
    accent: "#4479A1",
  },
];

export const SocialLink = [
  {
    photosource: "/icons8-facebook.svg",
    alt: "Facebook Logo",
    link: "https://web.facebook.com/JoshtheOG",
  },
  {
    photosource: "/githubLogo.png",
    alt: "Github Logo",
    link: "https://github.com/Joshking21",
  },
  {
    photosource: "/Twitter.png",
    alt: "Twitter Logo",
    link: "https://x.com/Joshking2105",
  },
];

export const SocialLinkWhite = [
  {
    photosource: "/facebookWhite.png",
    alt: "Facebook Logo",
    link: "https://web.facebook.com/JoshtheOG",
  },
  {
    photosource: "/gitHubWhite.png",
    alt: "Github Logo",
    link: "https://github.com/Joshking21",
  },
  {
    photosource: "/twitterWhite.png",
    alt: "Twitter Logo",
    link: "https://x.com/Joshking2105",
  },
];
