export const ProjectDetails= [
    {
        ProjectName: "Pig Games",
        ProjectImage: "",
        ProjectLink:"https://pig-games2-ilodl48bo-joshs-projects-655a25cc.vercel.app/",
        ProjectGitHubLink:"https://github.com/Joshking21/pigGames2"
    },
    {
        ProjectName:" Bankist Website",
        ProjectImage:"",
        ProjectLink:"https://new-bank-project-l27iuldk0-joshs-projects-655a25cc.vercel.app/",
        ProjectGitHubLink:"https://github.com/Joshking21/NewBankProject"
    },
    {
        ProjectName:" Event Website",
        ProjectImage:"",
        ProjectLink:"",
        ProjectGitHubLink:""
    }
]